services:
  db:
    image: postgres:15
    container_name: pos_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - pos_data:/var/lib/postgresql/data
    networks:
      - pos-net

  app:
    build:
      context: .
    command: sh -c "node src/infrastructure/seed.js && npm run dev"
    container_name: pos_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    stdin_open: true
    networks:
      - pos-net

volumes:
  pos_data:

networks:
  pos-net:
