networks:
  pos-net: null
services:
  app1:
    build:
      context: .
    command: sh -c 'node src/infrastructure/seed.js && npm run dev'
    container_name: app1
    depends_on:
    - db
    - redis
    expose:
    - '3000'
    networks:
    - pos-net
    volumes:
    - .:/usr/src/app
    working_dir: /usr/src/app
  stock-service:
    build:
      context: ./stock-service
    command: npm run dev
    container_name: stock-service
    depends_on:
      - db
      - redis
    networks:
      - pos-net
    ports:
      - "3010:3000"  # Pour l'exposer localement sur un port différent
    volumes:
      - ./stock-service:/usr/src/app
    working_dir: /usr/src/app
  db:
    container_name: pos_pg
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15
    networks:
    - pos-net
    ports:
    - 5432:5432
    restart: always
    volumes:
    - pos_data:/var/lib/postgresql/data
  grafana:
    container_name: grafana
    depends_on:
    - prometheus
    image: grafana/grafana
    networks:
    - pos-net
    ports:
    - 3001:3000
    volumes:
    - grafana-storage:/var/lib/grafana
  nginx:
    container_name: nginx
    depends_on:
    - app1
    - app2
    - app3
    image: nginx:alpine
    networks:
    - pos-net
    ports:
    - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
    - pos-net
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  redis:
    container_name: redis
    image: redis:7
    networks:
    - pos-net
    ports:
    - 6379:6379
version: '3.8'
volumes:
  grafana-storage: null
  pos_data: null
