{
 "title": "LOG430 - Golden Signals - Responsive",
 "tags": [
  "log430",
  "prometheus"
 ],
 "time": { "from": "2025-07-16T18:01:30.421Z", "to": "2025-07-16T18:03:59.612Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latence HTTP (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Requêtes totales /s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Taux erreurs 4xx/5xx /s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=~\"4..|5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Répartition des codes HTTP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (code)"
    }
   ]
  }
 ]
}